---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:jaack1/vector-role.git
    scm: git
    version: "1.01"
    name: vector

  - src: git@github.com:jaack1/lighthouse-role.git
    scm: git
    version: "1.01"
    name: lighthouse