---
  some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36393738386264326465333230616435356236613132356332356539356263363936386361633835
          3031336233363161653438663636393438663965353563300a626462333935353534653532313439
          66316362363564646433323361616333646364643461666138386232646338323063333461653564
          3166396130326632330a373437336136613037393130363964623739386163353536343166623561
          6534