---
  some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653033353366613962393966346434313132656462393264656537343162613466653130623939
          6231623665666133333861636364333731363766343434620a313731363163396636396336363932
          38663632363332636663346664633730643134333137393065613532363334643230623535383161
          6436313062613265340a653335363430383234336539623935313762613131393139653063323233
          32396535366338396136303263363464653730353931613264633166356330363665